### ISSUE TITLE
Create snap for feedreader

### ISSUE THREAD

**Issue by lightonflux** [jangernert/FeedReader#268]
Here my first try getting a more complex application snapped. At the moment it compiles without complains but exits with an error.

Here the current snapcraft file which compiles well under Ubuntu 16.10.

```

name: feedreader-snap
version: '0.1'
summary: FeedReader is a desktop application to complement  RSS accounts.
description: |
  Mindblowing good description of feedreader the awesome feedreader app.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  feedreader-snap:
    command: bin/feedreader
    plugs: [home, unity7, x11, gsettings, network]
  env: # for testing
    command: env

parts:
  feedreader:
    plugin: cmake
    configflags: ["-DUSE_WEBKIT_4=ON -DWITH_LIBUNITY=OFF"]
    source: https://github.com/jangernert/FeedReader.git
    build-packages:
      - build-essential
      - cmake
      - valac
      - pkg-config
      - libgirepository1.0-dev
      - libgtk-3-dev
      - libsoup2.4-dev
      - libjson-glib-dev
      - libwebkit2gtk-4.0-dev
      - libsqlite3-dev
      - libsecret-1-dev
      - libnotify-dev
      - libxml2-dev
      - librest-dev
      - libgee-0.8-dev
      - libcurl4-gnutls-dev
      - libgstreamer-plugins-base1.0-dev
      - libpeas-dev
      - libgoa-1.0-dev
```

The error when running:

```

$ feedreader-snap
(feedreader:2195): Gtk-WARNING **: Locale not supported by C library.
        Using the fallback 'C' locale.

(feedreader:2195): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
Trace/breakpoint trap (core dumped)

```

Will investigate further later. But if you have an idea what the problem is please tell. Do we need to package the gsetting schemas? If so how do i generate the schemas?
